### ISSUE TITLE
Typo when axe is picked up

### ISSUE THREAD

**Issue by rikkutoa** [vvroul/AlterationRPG#1]
When the player picks up said item "Axe" should said item be called Pick Axe?
I don't mean to be nit picky but I was just pointing it out

**Comment by vvroul** [comment]
@rikkutoa Yeah, you're right, just wanted to test things out with an axe as weapon and ended up using a pickaxe as a tile! It's just a sample dungeon at the moment, just testing things out. Thanks for the point! 

Edit : Added a Pickaxe as a general item, for the hero to pick up instead of an axe!
